// IMP!
// Kafka handles writing data into our system, while
// Redis and Postgres handle reading data out to our users.

import crypto from "node:crypto";
import { redis } from "./redis.js";

// Cache Stampede Protection:
// also known as the Cache-Aside with Distributed Locking pattern
//
// 10,000 Dashboard Users ──(Click Refresh at 12:00:00)──►  Dashboard API (/charts/traffic)
// The Dashboard Side (What Redis & Postgres Handle)
// Now, Imagine we are a business manager opening our analytics screen.
// Our web browser hits our Dashboard API endpoint (/charts/traffic) to read the data graph.
// Suddenly, our company goes viral. 10,000 managers open their dashboard screen at the exact same second
// to look at the chart.
// The Nightmare Scenario (If the Cache Expires at 12:00:00)
// The 30-second Redis cache timer hits zero and vanishes.
// 10,000 requests hit our Dashboard API at the exact same millisecond.
// They all look at Redis. Cache Miss!All 10,000 requests bypass the cache and
// fire complex SELECT SUM(views)... queries directly to Postgres at the exact same time.
//
// Enter the Lock Code (getWithLock)
// Our cache stampede lock code acts as a safety shield for reads.
// When those 10,000 managers hit the dashboard at the exact same second:
// Instead of 10,000 heavy queries smashing our database at once, exactly 1 request touches Postgres.
// The other 9,999 requests sit patiently in a loop for a few milliseconds,
// wake up, and pull the pre-computed answer cleanly out of Redis.
//
// Redis Locks prevent our database from crashing when too many people are viewing dashboards (Reading).
//
// This line of code is creating a Distributed Lock using Redis.
// It is a highly effective way to prevent two different servers or background workers
// from doing the exact same task at the exact same time.
//
// lockKey (The Room Number): The unique name for the resource you want to protect
// (e.g., "lock:process-traffic-metrics").
//
// lockToken (The Key Card): A unique string (usually a random UUID) generated by your server.
// It proves that our specific container owns the lock so you don't accidentally unlock someone else's
// room later.
//
// NX: true (Only if it doesn't exist): This stands for "Not eXists".
// It tells Redis: "Only save this lockKey if nobody else has saved it yet.
// "If the lock is free, Redis saves it and returns "OK".
// If another server is already working on it, Redis refuses to overwrite it and returns null.
//
// PX: 5000 (The Expiry Date): This is a safety timeout set in milliseconds (5000ms = 5 seconds).
// It tells Redis to automatically delete this lock key after 5 seconds no matter what.
//
// STALE CACHE
// Short TTL
//   OR
// await redis.del(
//     "pulse:chart:traffic:1h"
// );
// EX: 30,

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

interface GetWithLockOptions<T> {
  key: string;
  ttlSeconds: number;
  loader: () => Promise<T>;
}

export const getWithLock = async <T>({
  key,
  ttlSeconds,
  loader,
}: GetWithLockOptions<T>): Promise<T> => {
  // Initial Quick Cache Check
  const cached = await redis.get(key);
  if (cached !== null) {
    return JSON.parse(cached) as T;
  }

  const lockKey = `lock:${key}`;
  const token = crypto.randomUUID();

  //   Attempt to acquire the exclusive building lock
  const lockAcquired = await redis.set(lockKey, token, {
    // NX: true shield,
    // Redis treated the lock key like a concrete wall.
    // When Server B knocked a millisecond later,
    // Redis saw that Server A had already claimed the room, so it rejected Server B instantly
    //
    // When Server A finishes its database query,
    // it sends its private uuid-111 token to the Lua script.
    // Redis checks the folder: "Does the token inside match uuid-111?"
    // If yes, it deletes it.
    // This prevents Server A from accidentally deleting the lock if Server B managed to break in later
    // due to a timeout loop
    //
    //  Server A ───► [ SET lock:chart "uuid-111" NX ] ───►  REDIS ───► Empty! -> Saves it. Returns "OK"
    //                                                          │
    //                                                          ▼
    //  Server B ───► [ SET lock:chart "uuid-222" NX ] ───►  REDIS ───► Occupied! -> Rejects. Returns null
    NX: true,
    PX: 5000, // 5-second safety timeout
  });

  if (lockAcquired) {
    try {
      // Double Check: Has another thread built the cache while we waited for the lock?
      const secondCheck = await redis.get(key);
      if (secondCheck !== null) {
        return JSON.parse(secondCheck) as T;
      }

      // Execute the database loader function
      const data = await loader();

      // Write results to cache with provided expiration time
      await redis.set(key, JSON.stringify(data), {
        EX: ttlSeconds,
      });

      return data;
    } finally {
      // Safely release only our lock
      await releaseLock(lockKey, token);
    }
  }

  // Lock was busy. Poll Redis every 50ms for up to 500ms waiting for the winner to finish
  for (let attempt = 0; attempt < 10; attempt++) {
    await sleep(50);
    const value = await redis.get(key);
    if (value !== null) {
      return JSON.parse(value) as T;
    }
  }

  console.warn(
    `Lock timeout for key [${key}]. Falling back directly to database loader.`,
  );
  return loader();
};

// The Acquisition (lockKey protects the database)
// When Server A races to run a dashboard query,
// it creates the lockKey folder in Redis and writes its private token inside it [M1].
// When Server B arrives a millisecond later and asks for that same lockKey,
// Redis looks at the door name, sees it is occupied, and blocks Server B instantly
//
// The Release (token protects the server)
// Imagine Server A runs so slowly that its safety timeout expires,
// and Redis wipes the lock to prevent a system freeze.
// Server B immediately steps in and creates the exact same lockKey name,
// but writes its own new token inside it.
// When Server A finally wakes up from its delay and tries to leave, it tells the Lua script to target lockKey.
// If it blindly targeted the lockKey name alone, it would delete the folder and destroy Server B's active session.
// By checking the token,
// Redis can verify: "The current key card in this door belongs to Server B (token B), but Server A (token A)
// is trying to open it.
// Access Denied."The lockKey keeps your servers from running the same job at the same time,
// while the token keeps your servers from accidentally clean-wiping each other's security states [M1]
//
export const releaseLock = async (
  lockKey: string,
  token: string,
): Promise<void> => {
  // Executes atomic evaluation on the Redis engine directly
  // With LUA script
  //
  // await redis.eval(...):
  // This tells our Node.js application to stop sending standard individual commands and
  // instead inject a full Lua script block directly into the core execution engine of Redis.
  //
  // redis.call("GET", KEYS[1]):
  // Redis opens the very first key we passed in the array (KEYS[1]),
  // which is our unique lockKey string (e.g., "lock:pulse:chart").
  // It reads the UUID token currently stored inside it.== ARGV[1]:
  // It instantly compares that stored token against the first argument string we passed (ARGV[1]),
  // which is our server's private token UUID.
  // then return redis.call("DEL", KEYS[1]):
  // If the two UUID strings are an exact match, the script immediately fires the DEL (Delete) command on that
  // exact key.
  // The lock vanishes, and the door opens instantly for other servers to work.
  // else return 0 end:
  // If the tokens do not match
  // meaning the lock was automatically deleted because our query took too long, and
  // a new server has since taken over the lock, the script returns a 0 value and
  // refuses to touch or delete the key.
  await redis.eval(
    `
    if redis.call("GET", KEYS[1]) == ARGV[1]
    then
        return redis.call("DEL", KEYS[1])
    else
        return 0
    end
`,
    {
      keys: [lockKey],
      arguments: [token],
    },
  );
};
